### 행열(Matrix): 2차원 배열

In [1]:
x <- matrix(1:6)  # 1 ~ 6, 열로 입력
x # 세로 방향으로 1~6
nrow(x)  # 6행
ncol(x) # 1열

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

[1] 6

[1] 1

In [2]:
x <- matrix(1:6, nrow=2)  # 2행 3열, 행의 수 지정
x
# 1	3	5
# 2	4	6


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [3]:
names <- list(c("stu1", "stu2", "stu3"), c("R", "PYTHON", "AI"))
names  # 행 index, 열 index에 이름을 적용 가능
# 'stu1' 'stu2' 'stu3'
# 'R' 'PYTHON' 'AI'

x <- matrix(1:9, nrow=3, dimnames = names) # 열방향 우선** 할당
x
# R	PYTHON	AI
# stu1	1	4	7
# stu2	2	5	8
# stu3	3	6	9


[[1]]
[1] "stu1" "stu2" "stu3"

[[2]]
[1] "R"      "PYTHON" "AI"

R PYTHON AI
stu1 1 4      7 
stu2 2 5      8 
stu3 3 6      9

In [4]:
names <- list(c("stu1", "stu2", "stu3"), c("R", "PYTHON", "AI"))
x <- matrix(1:9, nrow=3, dimnames = names, byrow = TRUE) # 행방향 우선할당
x
class(x) # 'matrix'
# R	PYTHON	AI
# stu1	1	2	3
# stu2	4	5	6
# stu3	7	8	9


R PYTHON AI
stu1 1 2      3 
stu2 4 5      6 
stu3 7 8      9

[1] "matrix"

In [5]:
v1 <- c(1, 2 ,3)
v2 <- c(4, 5 ,6)
v3 <- c(7, 8 ,9)
x <- cbind(v1, v2, v3) # 열방향 합침, 컬럼이 증가됨.
x
# v1	v2	v3
# 1	4	7
# 2	5	8
# 3	6	9


v1 v2 v3
[1,] 1  4  7 
[2,] 2  5  8 
[3,] 3  6  9

In [6]:
x <- rbind(v1, v2, v3) # 행방향 합침, 행이 증가됨.
x
class(x)
# v1	1	2	3
# v2	4	5	6
# v3	7	8	9


[,1] [,2] [,3]
v1 1    2    3   
v2 4    5    6   
v3 7    8    9

[1] "matrix"

In [7]:
x <- matrix(10:19, 2)  # 기본적으로 열방향 할당
x
# 10	12	14	16	18
# 11	13	15	17	19


[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

In [8]:
x[1, ]  # 1행의 모든열
# 10 12 14 16 18
x[, 5]  # 모든행의 5열
# 18 19
x[2, 3] # 15, index는 1부터 시작
# 15
x[1, c(2:5)] # 1행, 여러개의 열 index를 vector로 선언
# 12 14 16 18

[1] 10 12 14 16 18

[1] 18 19

[1] 15

[1] 12 14 16 18

In [9]:
length(x)
# 10
nrow(x)
# 2
ncol(x)
# 5

[1] 10

[1] 2

[1] 5

In [10]:
x <- matrix(1:15, 3)
x
# 1	4	7	10	13
# 2	5	8	11	14
# 3	6	9	12	15

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

In [14]:
maxs = apply(x, 1, max)  # 행단위(1) 최댓값 산출
maxs
# 13 14 15
mode(maxs)
# 'numeric'
class(maxs)
# 'integer'
maxs[1]
# 13
apply(x, 1, min)  # 행단위(1) 최솟값 산출
# 1 2 3

[1] 13 14 15

[1] "numeric"

[1] "integer"

[1] 13

[1] 1 2 3

In [12]:
apply(x, 1, mean) # 행단위(1) 평균 산출
# 7 8 9
apply(x, 1, var)  # 행단위(1) 분산 산출
# 22.5 22.5 22.5
apply(x, 1, sd)   # 행단위(1) 표준편차 산출
# 4.74341649025257 4.74341649025257 4.74341649025257

[1] 7 8 9

[1] 22.5 22.5 22.5

[1] 4.743416 4.743416 4.743416

In [13]:
apply(x, 2, max)  # 열단위(2) 최댓값 산출
# 3 6 9 12 15
apply(x, 2, min)  # 열단위(2) 최솟값 산출
# 1 4 7 10 13
apply(x, 2, mean) # 열단위(2) 평균 산출
# 2 5 8 11 14
apply(x, 2, var)  # 열단위(2) 분산 산출
# 1 1 1 1 1
apply(x, 2, sd)   # 열단위(2) 표준편차 산출
# 1 1 1 1 1

[1]  3  6  9 12 15

[1]  1  4  7 10 13

[1]  2  5  8 11 14

[1] 1 1 1 1 1

[1] 1 1 1 1 1

### 배열(Array)

In [27]:
x <- array(1:3, dim=c(3))
x
# 1 2 3
x <- array(1:10, dim=c(5)) # 차원 정보, 1차원 데이터의 갯수
x
# 1 2 3 4 5

[1] 1 2 3

[1] 1 2 3 4 5

In [30]:
x <- array(1:10, dim=c(2, 3)) # 2차원, 2행 3열
x
# 1	3	5
# 2	4	6

x <- array(1:10, dim=c(2, 5)) # 2차원, 2행 5열
x
# 1	3	5	7	9
# 2	4	6	8	10


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [15]:
# [차원 위키] Google 검색
x <- array(1:20, dim=c(2, 3, 3))  # 2행 x 3열 x 3면 = 18, 열우선 값 저장
x
# 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
# 데이터가 넘칠 시 잘라냄

x <- array(1:20, dim=c(2, 3, 4))  # 2행 x 3열 x 4면 = 24, 열우선 값 저장
x
# 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 1 2 3 4
# 데이터 부족시 순환됨

nrow(x) # 2
ncol(x) # 3
dim(x) # 2 3 4

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19    1    3
[2,]   20    2    4

[1] 2

[1] 3

[1] 2 3 4

In [16]:
print(x)
# 보통 다른 언어: 면->행->열
# R: 행->열->면
# , , 1

#      [,1] [,2] [,3]
# [1,]    1    3    5
# [2,]    2    4    6

# , , 2

#      [,1] [,2] [,3]
# [1,]    7    9   11
# [2,]    8   10   12

# , , 3

#      [,1] [,2] [,3]
# [1,]   13   15   17
# [2,]   14   16   18

# , , 4

#      [,1] [,2] [,3]
# [1,]   19    1    3
# [2,]   20    2    4

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19    1    3
[2,]   20    2    4



In [17]:
# 2행 3열 3면 3차원의 갯수, 열방향 값(2) 저장
x <- array(1:20, dim=c(2, 3, 3, 2))  
x

, , 1, 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2, 1

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3, 1

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 1, 2

     [,1] [,2] [,3]
[1,]   19    1    3
[2,]   20    2    4

, , 2, 2

     [,1] [,2] [,3]
[1,]    5    7    9
[2,]    6    8   10

, , 3, 2

     [,1] [,2] [,3]
[1,]   11   13   15
[2,]   12   14   16

In [18]:
print(x)

, , 1, 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2, 1

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3, 1

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 1, 2

     [,1] [,2] [,3]
[1,]   19    1    3
[2,]   20    2    4

, , 2, 2

     [,1] [,2] [,3]
[1,]    5    7    9
[2,]    6    8   10

, , 3, 2

     [,1] [,2] [,3]
[1,]   11   13   15
[2,]   12   14   16



In [19]:
x <- array(10:20, dim=c(2, 3))
x
# 10	12	14
# 11	13	15


[,1] [,2] [,3]
[1,] 10   12   14  
[2,] 11   13   15

In [48]:
x[1]  # 모든 데이터를 열발향 접근, 데이터 많을시 사용 어려움
x[2]
x[3]

[1] 10

[1] 11

[1] 12

In [49]:
x[1,]  # 1행
# 10 12 14

[1] 10 12 14

In [50]:
x[, 1] # 1열
# 10 11

[1] 10 11

In [51]:
x[1,1] # 1행 1열

[1] 10

In [52]:
x[, -3] # 3열 제외하고 출력
# 10	12
# 11	13


[,1] [,2]
[1,] 10   12  
[2,] 11   13

In [20]:
names <- list(c("stu1", "stu2"), c("r", "python", "ai"))
x <- array(c(1:6), dim=c(2,3)) # 1부터 index 적용
print(x)
#      [,1] [,2] [,3]
# [1,]    1    3    5
# [2,]    2    4    6
x <- array(c(1:6), dim=c(2,3), dimnames = names) # index 이름 지정
print(x)
#      r python ai
# stu1 1      3  5
# stu2 2      4  6

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     r python ai
stu1 1      3  5
stu2 2      4  6


In [58]:
x['stu1',] # stu1행의 모든 컬럼

r python     ai 
     1      3      5

In [60]:
x[,'r'] # r 컬럼의 모든 행

stu1 stu2 
   1    2

In [62]:
x <- array(1:3, dim=c(3))
x
x[1] <- 'Jupyter' # 수치형 배열에 문자열 할당시 모두 문자열로 변경됨.
x

[1] 1 2 3

[1] "Jupyter" "2"       "3"