## 다층 퍼셉트론을 이용한 XOR 문제의 해결

In [10]:
# AND

def AND(x1, x2):
    w1, w2, theta = .4, .4, .7
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1

print(AND(0,0), AND(0,1), AND(1,0), AND(1,1))


0 0 0 1


In [2]:
# OR

def OR(x1, x2):
    w1, w2, theta = .4, .4, .3
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1

print(OR(0,0), OR(0,1), OR(1,0), OR(1,1))


0 1 1 1


In [3]:
# NAND

def NAND(x1, x2):
    w1, w2, theta = -.4, -.4, -.6
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1


print(NAND(0,0), NAND(0,1), NAND(1,0), NAND(1,1))


1 1 1 0


In [4]:
# NAND, OR, AND 결합한 XOR 코드

import numpy as np 
import matplotlib.pyplot as plt

def AND(x1, x2):
    w1, w2, theta = .4, .4, .7
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1

def OR(x1, x2):
    w1, w2, theta = .4, .4, .3
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1

def NAND(x1, x2):
    w1, w2, theta = -.4, -.4, -.6
    if x1*w1 + x2*w2 <= theta:
        return 0
    else :
        return 1

def XOR(x1, x2):
    h1 = NAND(x1, x2)
    h2 = OR(x1, x2)
    return AND(h1, h2)

print(XOR(0,0), XOR(0,1), XOR(1,0), XOR(1,1))


0 1 1 0


In [11]:
# 다층 퍼셉트론 함수 선언

import numpy as np

def DLPerceptron(X, W1, W2):
    x = np.array(X)
    w1 = np.array(W1)
    w2 = np.array(W2)
    h1 = np.array([0.0]*len(X))
    y = np.array([0.0]*len(X))
    for count in range(len(X)):
        h1[count] = np.sum(x*w1[count]) > 0
    for count in range(len(x)):
        y[count] = np.sum(h1*w2[count]) > 0
        
    print(h1)    
    print(y)    
    return y


In [12]:
W1 = [[-0.4, -0.4, 0, 0, 0, 0.6],
[0.4, 0.4, 0, 0, 0, -0.3],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 1]]

W2 = [[0.4, 0.4, 0, 0, 0, -0.7],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]]

Ex00 = [0,0,0,0,0,1]
Ex01 = [0,1,0,0,0,1]
Ex10 = [1,0,0,0,0,1]
Ex11 = [1,1,0,0,0,1]

print("x1, x2 = (0, 0) : ", DLPerceptron(Ex00,W1,W2))
print("x1, x2 = (0, 1) : ", DLPerceptron(Ex01,W1,W2))
print("x1, x2 = (1, 0) : ", DLPerceptron(Ex10,W1,W2))
print("x1, x2 = (1, 1) : ", DLPerceptron(Ex11,W1,W2))


[1. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0.]
x1, x2 = (0, 0) :  [0. 0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0.]
x1, x2 = (0, 1) :  [1. 0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 1.]
[1. 0. 0. 0. 0. 0.]
x1, x2 = (1, 0) :  [1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0.]
x1, x2 = (1, 1) :  [0. 0. 0. 0. 0. 0.]
